/**********************************************************************************************************************
 *  FILE DESCRIPTION
 *  -------------------------------------------------------------------------------------------------------------------
 *  File: SysKineAndEff.c
 *  SW-C Type:SysKineAndEff
 *  C/C++ source code generated on : Thu Apr 19 10:18:59 2018
   Code generated for Simulink model 'SysKineAndEff'.
 ***********************************************************************************************************************
   Tool Information
 *-----------------------------------------------------------------------------------------------------------------------
 * Simulink Coder version         : 8.13 (R2017b) 24-Jul-2017
 **********************************************************************************************************************
 * Copyright '2018' Nxtr
 * Nxtr Confidential
 *
 * Module File Name  : SysKineAndEff.c
 * Module Description: In a variable ratio system the kinematic ratio and mechanical efficiency of  the input and motor torque can change as the rack moves.
   This component calculates the Efficiencies and Ratios based on the Rack movement.
 * Project           : CBD
 * Author            : Nimmy M
 ***********************************************************************************************************************
 * Version Control:
 * %version:  		2%
 * %derived_by:    dzvc93 %
 **********************************************************************************************************************
 * CHANGE LOG COPIED FROM SIMULINK MODEL
 *---------------------------------------
 * Change Log

   Ver 1.1.0
   Author :Nimmy Mathews
   Date : 17 April 2018
   Change Control #: EA4#22824
   Description : Design updated to add Limiter block to avoid overflow

   Ver 1.0.1
   Author :Vipin David (TataElxsi)
   Date : 24 Mar 2018
   Change Control #: EA4#21991
   Description : Design updated for autocoding without any functionality change.

   Ver 1.0.0
   Author :Dinesh Mankar (KPIT)/ Poonam Chavan (KPIT)
   Date : 20-Mar-2018
   Change Control #: EA4#19300, EA4#19825
   Description : Initial version of EA4 Design from Requirment baseline v2.1
 **********************************************************************************************************************/
/*********************File Level Rule Deviations**********************************************************************/

/* MISRA-AGC Rule 16.10 [NXTRDEV 16.10.1]: There is no appropriate action to take on the return value for Rte_Read, Rte_Write */
/* MISRA-AGC Rule 19.1  [NXTRDEV 19.1.1]:  AUTOSAR requires deviation from this rule for Memory Mapping include statements */

/* MISRA-AGC Rule 8.1   [NXTRDEV 8.1.1] :  Deviation for autocode only, due to tools limitation.
   ‘_Init’ function does not have a declaration/prototype in autocode. This init function is generated by embedded coder and is not present in the Simulink model.
   This function is always empty and is not called */

/* MISRA-AGC Rule 8.10  [NXTRDEV 8.10.2]:  Deviation for autocode only, due to tools limitation.
   ‘_Init’ function is not defined as “static” even though no external linkage is required. This init function is generated by embedded coder and is not present in the Simulink model.
   This function is always empty and is not called */

/*********************End of File Level Rule Deviations***************************************************************/
#include "SysKineAndEff.h"
#define SysKineAndEff_START_SEC_CODE
#include "SysKineAndEff_MemMap.h"

/*
 * Check that imported macros with storage class "ImportedDefine" are defined
 */
#ifndef ARCHGLBPRM_2MILLISEC_SEC_F32
#error The variable for the parameter "ARCHGLBPRM_2MILLISEC_SEC_F32" is not defined
#endif

#ifndef NXTRFIXDPT_FLOATTOP0_ULS_F32
#error The variable for the parameter "NXTRFIXDPT_FLOATTOP0_ULS_F32" is not defined
#endif

#ifndef NXTRFIXDPT_FLOATTOP7_ULS_F32
#error The variable for the parameter "NXTRFIXDPT_FLOATTOP7_ULS_F32" is not defined
#endif

#ifndef NXTRFIXDPT_P11TOFLOAT_ULS_F32
#error The variable for the parameter "NXTRFIXDPT_P11TOFLOAT_ULS_F32" is not defined
#endif

#ifndef NXTRFIXDPT_P12TOFLOAT_ULS_F32
#error The variable for the parameter "NXTRFIXDPT_P12TOFLOAT_ULS_F32" is not defined
#endif

#ifndef NXTRFIXDPT_P13TOFLOAT_ULS_F32
#error The variable for the parameter "NXTRFIXDPT_P13TOFLOAT_ULS_F32" is not defined
#endif

#ifndef NXTRFIXDPT_P15TOFLOAT_ULS_F32
#error The variable for the parameter "NXTRFIXDPT_P15TOFLOAT_ULS_F32" is not defined
#endif

#ifndef NXTRFIXDPT_P7TOFLOAT_ULS_F32
#error The variable for the parameter "NXTRFIXDPT_P7TOFLOAT_ULS_F32" is not defined
#endif

/* Exported data define */

/* Definition for custom storage class: Const_Local */
#define CNVTOMTR_ULS_F32               ((float32)(0.001F))
#define COMPLNCERRPINIONTOHWDERIVTVMAXVAL_HWRADPERSEC_F32 ((float32)(100.0F))
#define COMPLNCERRPINIONTOHWDERIVTVMINVAL_HWRADPERSEC_F32 ((float32)(-100.0F))
#define DIVBYVAL_ULS_F32               ((float32)(2.0F))
#define HALFDIVBYPI_ULS_F32            ((float32)(0.1592F))
#define HWAGMAXVAL_HWDEG_F32           ((float32)(1440.0F))
#define HWAGMINVAL_HWDEG_F32           ((float32)(-1440.0F))
#define HWVELMAXVAL_HWRADPERSEC_F32    ((float32)(42.0F))
#define HWVELMINVAL_HWRADPERSEC_F32    ((float32)(-42.0F))
#define MOTAGCUMVALGNDMRFMAXVAL_MOTDEG_F32 ((float32)(32767.0F))
#define MOTAGCUMVALGNDMRFMINVAL_MOTDEG_F32 ((float32)(-32767.0F))
#define MOTAGTORACKPOSNINSTSRATMAXVAL_RACKMILLIMTRPERMOTRAD_F32 ((float32)(3.0F))
#define MOTAGTORACKPOSNINSTSRATMINVAL_RACKMILLIMTRPERMOTRAD_F32 ((float32)(0.01F))
#define MOTTORACKFINSTSRATMAXVAL_RACKNWTPERMOTNWTMTR_F32 ((float32)(4400.0F))
#define MOTTORACKFINSTSRATMINVAL_RACKNWTPERMOTNWTMTR_F32 ((float32)(1860.0F))
#define MOTTORACKINSTSEFFMAXVAL_ULS_F32 ((float32)(1.0F))
#define MOTTORACKINSTSEFFMINVAL_ULS_F32 ((float32)(0.1F))
#define PINIONAGTORACKINSTSEFFMAXVAL_ULS_F32 ((float32)(1.0F))
#define PINIONAGTORACKINSTSEFFMINVAL_ULS_F32 ((float32)(0.1F))
#define PINIONAGTORACKPOSNINSTRATMAXVAL_RACKMILLIMTRPERHWRAD_F32 ((float32)(20.0F))
#define PINIONAGTORACKPOSNINSTRATMINVAL_RACKMILLIMTRPERHWRAD_F32 ((float32)(1.0F))
#define PINIONTQTORACKINSTSRATMAXVAL_RACKNWTPERHWNWTMTR_F32 ((float32)(300.0F))
#define PINIONTQTORACKINSTSRATMINVAL_RACKNWTPERHWNWTMTR_F32 ((float32)(60.0F))
#define PINIONVELMAXVAL_HWRADPERSEC_F32 ((float32)(42.0F))
#define PINIONVELMINVAL_HWRADPERSEC_F32 ((float32)(-42.0F))
#define RACKPOSNMAXVAL_MILLIMTR_F32    ((float32)(200.0F))
#define RACKPOSNMINVAL_MILLIMTR_F32    ((float32)(-200.0F))
#define RACKVELMAXVAL_MILLIMTRPERSEC_F32 ((float32)(500.0F))
#define RACKVELMINVAL_MILLIMTRPERSEC_F32 ((float32)(-500.0F))
#define ROADWHLAGMAXVAL_RAD_F32        ((float32)(1.57F))
#define ROADWHLAGMINVAL_RAD_F32        ((float32)(-1.57F))
#define STEERARMLENMAXVAL_MILLIMTR_F32 ((float32)(300.0F))
#define STEERARMLENMINVAL_MILLIMTR_F32 ((float32)(25.0F))
#define SYSASSITQRATMAXVAL_HWNWTMTRPERMOTNWTMTR_F32 ((float32)(50.0F))
#define SYSASSITQRATMINVAL_HWNWTMTRPERMOTNWTMTR_F32 ((float32)(10.0F))
#define SYSKINERATMAXVAL_MOTDEGPERHWDEG_F32 ((float32)(50.0F))
#define SYSKINERATMINVAL_MOTDEGPERHWDEG_F32 ((float32)(10.0F))
#define SYSTQRATMAXVAL_HWNWTMTRPERMOTNWTMTR_F32 ((float32)(50.0F))
#define SYSTQRATMINVAL_HWNWTMTRPERMOTNWTMTR_F32 ((float32)(10.0F))

/* Model step function for TID1 */
FUNC(void, SysKineAndEff_CODE) SysKineAndEffInit1(void) /* Sample time: [0.002s, 0.0s] */
{
  /* (no output/update code required) */
}

/* Model step function for TID2 */
FUNC(void, SysKineAndEff_CODE) SysKineAndEffPer1(void) /* Sample time: [0.002s, 0.0s] */
{
  /* local block i/o variables */
  float32 rtb_Divide1;
  float32 rtb_Add_g;
  float32 rtb_Product1;
  float32 rtb_Product4;
  float32 rtb_Product_h;
  float32 rtb_Product3;
  float32 rtb_Product2;
  float32 rtb_Add_f;
  float32 rtb_FixdToFloat_f32_u16_p;
  float32 rtb_Lim_f32_k;
  float32 rtb_Divide;
  float32 rtb_Divide1_l;
  float32 rtb_FixdToFloat_f32_u16_b;
  float32 rtb_FixdToFloat_f32_s16_p;
  float32 rtb_FixdToFloat_f32_u16_g;
  sint16 rtb_LnrIntrpn_s16_s16VariXs16Va;
  sint16 rtb_FloatToFixd_s16_f32_i;
  sint32 tmpRead;
  float32 tmpRead_0;
  float32 tmpWrite;
  float32 tmpWrite_0;
  float32 tmpWrite_1;
  float32 tmpWrite_2;
  float32 tmpWrite_3;
  float32 tmpWrite_4;
  float32 tmpWrite_5;
  float32 tmpWrite_6;
  float32 tmpWrite_7;
  float32 tmpWrite_8;
  float32 tmpWrite_9;
  float32 tmpWrite_a;
  float32 tmpWrite_b;
  float32 tmpWrite_c;
  float32 tmpWrite_d;
  float32 rtb_DataStoreRead;
  float32 rtb_TmpSignalConversionAtCmplnc;
  float32 rtb_TmpSignalConversionAtMotVel;

  /* Inport: '<Root>/PinionAg' */
  Rte_Read_PinionAg_Val(&tmpRead_0);

  /* Inport: '<Root>/MotAgCumvAlgndMrf' */
  Rte_Read_MotAgCumvAlgndMrf_Val(&tmpRead);

  /* RootInportFunctionCallGenerator: '<Root>/RootFcnCall_InsertedFor_call_SysKineAndEffPer1_at_outport_1' incorporates:
   *  SubSystem: '<S2>/SysKineAndEffPer1'
   */
  /* DataStoreRead: '<S50>/DataStoreRead' */
  rtb_DataStoreRead = (*Rte_Pim_CmplncErrPinionToHwPrev());

  /* SignalConversion: '<S5>/TmpSignal ConversionAtCmplncErrPinionToHwOutport1' incorporates:
   *  Inport: '<Root>/CmplncErrPinionToHw'
   */
  Rte_Read_CmplncErrPinionToHw_Val(&rtb_TmpSignalConversionAtCmplnc);

  /* DataStoreWrite: '<S52>/DataStoreWrite' */
  (*Rte_Pim_CmplncErrPinionToHwPrev()) = rtb_TmpSignalConversionAtCmplnc;/* Product: '<S33>/Divide2' incorporates:
                                                                      *  Constant: '<S33>/Constant2'
                                                                      *  Constant: '<S33>/Constant3'
                                                                      */
  rtb_FixdToFloat_f32_s16_p = ((float32)ARCHGLBPRM_2MILLISEC_SEC_F32) /
    DIVBYVAL_ULS_F32;

  /* Product: '<S33>/Divide' incorporates:
   *  Constant: '<S33>/Constant1'
   *  Constant: '<S7>/Constant2'
   */
  rtb_FixdToFloat_f32_u16_g = HALFDIVBYPI_ULS_F32 /
    Rte_Prm_SysKineAndEffCmplncErrDerivtvCutOffFrq_Val();

  /* Product: '<S33>/Divide1' incorporates:
   *  DataStoreRead: '<S51>/DataStoreRead'
   *  Product: '<S33>/Product'
   *  Sum: '<S33>/Add'
   *  Sum: '<S33>/Add1'
   *  Sum: '<S33>/Add2'
   *  Sum: '<S33>/Add3'
   */
  rtb_Divide1 = ((rtb_TmpSignalConversionAtCmplnc - rtb_DataStoreRead) -
                 ((*Rte_Pim_CmplncErrDerivtvPrev()) * (rtb_FixdToFloat_f32_s16_p
    - rtb_FixdToFloat_f32_u16_g))) / (rtb_FixdToFloat_f32_s16_p +
    rtb_FixdToFloat_f32_u16_g);

  /* S-Function (Lim_f32): '<S54>/Lim_f32' incorporates:
   *  Constant: '<S54>/Constant'
   *  Constant: '<S54>/Constant1'
   */
  rtb_FixdToFloat_f32_u16_g = Lim_f32( (float32)rtb_Divide1, (float32)
    COMPLNCERRPINIONTOHWDERIVTVMINVAL_HWRADPERSEC_F32, (float32)
    COMPLNCERRPINIONTOHWDERIVTVMAXVAL_HWRADPERSEC_F32);

  /* DataStoreWrite: '<S53>/DataStoreWrite' */
  (*Rte_Pim_CmplncErrDerivtvPrev()) = rtb_FixdToFloat_f32_u16_g;/* SignalConversion: '<S5>/TmpSignal ConversionAtMotVelCrfOutport1' incorporates:
                                                                 *  Inport: '<Root>/MotVelCrf'
                                                                 */
  Rte_Read_MotVelCrf_Val(&rtb_TmpSignalConversionAtMotVel);

  /* S-Function (LnrIntrpn_s16_s16VariXs16VariY): '<S29>/LnrIntrpn_s16_s16VariXs16VariY' incorporates:
   *  Constant: '<S25>/Constant'
   *  Constant: '<S27>/Constant'
   *  Constant: '<S28>/Constant'
   *  Constant: '<S28>/Constant1'
   *  Constant: '<S29>/Constant'
   *  Constant: '<S29>/Constant1'
   *  Inport: '<Root>/MotAgCumvAlgndMrf'
   *  S-Function (FixdToFloat_f32_s32): '<S25>/FixdToFloat_f32_s32'
   *  S-Function (FloatToFixd_s16_f32): '<S27>/FloatToFixd_s16_f32'
   *  S-Function (Lim_f32): '<S28>/Lim_f32'
   */
  rtb_LnrIntrpn_s16_s16VariXs16Va = LnrIntrpn_s16_s16VariXs16VariY((const sint16*)
    Rte_Prm_SysKineAndEffMotAgScaX_Ary1D(), (const sint16*)
    Rte_Prm_SysKineAndEffRackPosScaY_Ary1D(),(uint16)21U, ((sint16)
    FloatToFixd_s16_f32( (float32)Lim_f32( (float32)FixdToFloat_f32_s32( (sint32)
    tmpRead, (float32)((float32)NXTRFIXDPT_P13TOFLOAT_ULS_F32)), (float32)
    MOTAGCUMVALGNDMRFMINVAL_MOTDEG_F32, (float32)
    MOTAGCUMVALGNDMRFMAXVAL_MOTDEG_F32), (float32)((float32)
    NXTRFIXDPT_FLOATTOP0_ULS_F32))));

  /* S-Function (FixdToFloat_f32_s16): '<S24>/FixdToFloat_f32_s16' incorporates:
   *  Constant: '<S24>/Constant'
   */
  rtb_FixdToFloat_f32_s16_p = FixdToFloat_f32_s16( (sint16)
    rtb_LnrIntrpn_s16_s16VariXs16Va, (float32)((float32)
    NXTRFIXDPT_P7TOFLOAT_ULS_F32));

  /* S-Function (FloatToFixd_s16_f32): '<S44>/FloatToFixd_s16_f32' incorporates:
   *  Constant: '<S44>/Constant'
   */
  rtb_FloatToFixd_s16_f32_i = FloatToFixd_s16_f32( (float32)
    rtb_FixdToFloat_f32_s16_p, (float32)((float32)NXTRFIXDPT_FLOATTOP7_ULS_F32));

  /* S-Function (FixdToFloat_f32_u16): '<S43>/FixdToFloat_f32_u16' incorporates:
   *  Constant: '<S43>/Constant'
   *  Constant: '<S49>/Constant'
   *  Constant: '<S49>/Constant1'
   *  S-Function (LnrIntrpn_u16_s16VariXu16VariY): '<S49>/LnrIntrpn_u16_s16VariXu16VariY'
   */
  rtb_FixdToFloat_f32_u16_p = FixdToFloat_f32_u16( (uint16)((uint16)
    LnrIntrpn_u16_s16VariXu16VariY((const sint16*)
    Rte_Prm_SysKineAndEffRackPosScaY_Ary1D(), (const uint16*)
    Rte_Prm_SysKineAndEffPinionAgToRackPosRatScaY_Ary1D(),(uint16)21U,
    rtb_FloatToFixd_s16_f32_i)), (float32)((float32)
    NXTRFIXDPT_P11TOFLOAT_ULS_F32));

  /* S-Function (Lim_f32): '<S45>/Lim_f32' incorporates:
   *  Constant: '<S42>/Constant'
   *  Constant: '<S45>/Constant'
   *  Constant: '<S45>/Constant1'
   *  Constant: '<S48>/Constant'
   *  Constant: '<S48>/Constant1'
   *  S-Function (FixdToFloat_f32_u16): '<S42>/FixdToFloat_f32_u16'
   *  S-Function (LnrIntrpn_u16_s16VariXu16VariY): '<S48>/LnrIntrpn_u16_s16VariXu16VariY'
   */
  rtb_Lim_f32_k = Lim_f32( (float32)FixdToFloat_f32_u16( (uint16)((uint16)
    LnrIntrpn_u16_s16VariXu16VariY((const sint16*)
    Rte_Prm_SysKineAndEffRackPosScaY_Ary1D(), (const uint16*)
    Rte_Prm_SysKineAndEffMotAgToRackPosRatScaY_Ary1D(),(uint16)21U,
    rtb_FloatToFixd_s16_f32_i)), (float32)((float32)
    NXTRFIXDPT_P12TOFLOAT_ULS_F32)), (float32)
    MOTAGTORACKPOSNINSTSRATMINVAL_RACKMILLIMTRPERMOTRAD_F32, (float32)
    MOTAGTORACKPOSNINSTSRATMAXVAL_RACKMILLIMTRPERMOTRAD_F32);

  /* Product: '<S38>/Divide' */
  rtb_Divide = rtb_FixdToFloat_f32_u16_p / rtb_Lim_f32_k;

  /* Product: '<S7>/Divide1' */
  rtb_Divide1_l = rtb_TmpSignalConversionAtMotVel / rtb_Divide;

  /* Sum: '<S7>/Add' */
  rtb_Add_g = rtb_Divide1_l + rtb_FixdToFloat_f32_u16_g;

  /* S-Function (FixdToFloat_f32_u16): '<S40>/FixdToFloat_f32_u16' incorporates:
   *  Constant: '<S40>/Constant'
   *  Constant: '<S46>/Constant'
   *  Constant: '<S46>/Constant1'
   *  S-Function (LnrIntrpn_u16_s16VariXu16VariY): '<S46>/LnrIntrpn_u16_s16VariXu16VariY'
   */
  rtb_FixdToFloat_f32_u16_g = FixdToFloat_f32_u16( (uint16)((uint16)
    LnrIntrpn_u16_s16VariXu16VariY((const sint16*)
    Rte_Prm_SysKineAndEffRackPosScaY_Ary1D(), (const uint16*)
    Rte_Prm_SysKineAndEffPinionToRackEffScaY_Ary1D(),(uint16)21U,
    rtb_FloatToFixd_s16_f32_i)), (float32)((float32)
    NXTRFIXDPT_P15TOFLOAT_ULS_F32));

  /* S-Function (FixdToFloat_f32_u16): '<S41>/FixdToFloat_f32_u16' incorporates:
   *  Constant: '<S41>/Constant'
   *  Constant: '<S47>/Constant'
   *  Constant: '<S47>/Constant1'
   *  S-Function (LnrIntrpn_u16_s16VariXu16VariY): '<S47>/LnrIntrpn_u16_s16VariXu16VariY'
   */
  rtb_FixdToFloat_f32_u16_b = FixdToFloat_f32_u16( (uint16)((uint16)
    LnrIntrpn_u16_s16VariXu16VariY((const sint16*)
    Rte_Prm_SysKineAndEffRackPosScaY_Ary1D(), (const uint16*)
    Rte_Prm_SysKineAndEffMotToRackEffScaY_Ary1D(),(uint16)21U,
    rtb_FloatToFixd_s16_f32_i)), (float32)((float32)
    NXTRFIXDPT_P15TOFLOAT_ULS_F32));

  /* Product: '<S34>/Product1' incorporates:
   *  Constant: '<S34>/Constant'
   */
  rtb_Product1 = (rtb_FixdToFloat_f32_u16_b / rtb_Lim_f32_k) / CNVTOMTR_ULS_F32;

  /* Product: '<S35>/Product4' incorporates:
   *  Constant: '<S35>/Constant1'
   */
  rtb_Product4 = (rtb_FixdToFloat_f32_u16_g / CNVTOMTR_ULS_F32) /
    rtb_FixdToFloat_f32_u16_p;

  /* Product: '<S36>/Product' */
  rtb_Product_h = rtb_Lim_f32_k * rtb_TmpSignalConversionAtMotVel;

  /* Outport: '<Root>/MotAgToRackPosnInstsRat' incorporates:
   *  SignalConversion: '<S7>/Signal Conversion'
   */
  (void) Rte_Write_MotAgToRackPosnInstsRat_Val(rtb_Lim_f32_k);

  /* Product: '<S37>/Product3' */
  rtb_Product3 = (rtb_Divide / rtb_FixdToFloat_f32_u16_b) *
    rtb_FixdToFloat_f32_u16_g;

  /* Product: '<S39>/Product2' */
  rtb_Product2 = (rtb_FixdToFloat_f32_u16_g * rtb_FixdToFloat_f32_u16_b) *
    rtb_Divide;

  /* Sum: '<S6>/Add' */
  rtb_Add_f = rtb_TmpSignalConversionAtCmplnc + tmpRead_0;

  /* S-Function (Lim_f32): '<S8>/Lim_f32' incorporates:
   *  Constant: '<S8>/Constant'
   *  Constant: '<S8>/Constant1'
   *  Outport: '<Root>/PinionVel'
   */
  tmpWrite_6 = Lim_f32( (float32)rtb_Divide1_l, (float32)
                       PINIONVELMINVAL_HWRADPERSEC_F32, (float32)
                       PINIONVELMAXVAL_HWRADPERSEC_F32);

  /* S-Function (Lim_f32): '<S9>/Lim_f32' incorporates:
   *  Constant: '<S9>/Constant'
   *  Constant: '<S9>/Constant1'
   *  Outport: '<Root>/PinionTqToRackFInstsRat'
   */
  tmpWrite_5 = Lim_f32( (float32)rtb_Product4, (float32)
                       PINIONTQTORACKINSTSRATMINVAL_RACKNWTPERHWNWTMTR_F32,
                       (float32)
                       PINIONTQTORACKINSTSRATMAXVAL_RACKNWTPERHWNWTMTR_F32);

  /* S-Function (Lim_f32): '<S10>/Lim_f32' incorporates:
   *  Constant: '<S10>/Constant'
   *  Constant: '<S10>/Constant1'
   *  Outport: '<Root>/SysTqRat'
   */
  tmpWrite_d = Lim_f32( (float32)rtb_Product2, (float32)
                       SYSTQRATMINVAL_HWNWTMTRPERMOTNWTMTR_F32, (float32)
                       SYSTQRATMAXVAL_HWNWTMTRPERMOTNWTMTR_F32);

  /* S-Function (Lim_f32): '<S11>/Lim_f32' incorporates:
   *  Constant: '<S11>/Constant'
   *  Constant: '<S11>/Constant1'
   *  Outport: '<Root>/SysAssiTqRat'
   */
  tmpWrite_b = Lim_f32( (float32)rtb_Product3, (float32)
                       SYSASSITQRATMINVAL_HWNWTMTRPERMOTNWTMTR_F32, (float32)
                       SYSASSITQRATMAXVAL_HWNWTMTRPERMOTNWTMTR_F32);

  /* S-Function (Lim_f32): '<S12>/Lim_f32' incorporates:
   *  Constant: '<S12>/Constant'
   *  Constant: '<S12>/Constant1'
   *  Outport: '<Root>/PinionAgToRackInstsEff'
   */
  tmpWrite_3 = Lim_f32( (float32)rtb_FixdToFloat_f32_u16_g, (float32)
                       PINIONAGTORACKINSTSEFFMINVAL_ULS_F32, (float32)
                       PINIONAGTORACKINSTSEFFMAXVAL_ULS_F32);

  /* S-Function (Lim_f32): '<S13>/Lim_f32' incorporates:
   *  Constant: '<S13>/Constant'
   *  Constant: '<S13>/Constant1'
   *  Outport: '<Root>/HwVel'
   */
  tmpWrite_0 = Lim_f32( (float32)rtb_Add_g, (float32)HWVELMINVAL_HWRADPERSEC_F32,
                       (float32)HWVELMAXVAL_HWRADPERSEC_F32);

  /* S-Function (Lim_f32): '<S14>/Lim_f32' incorporates:
   *  Constant: '<S14>/Constant'
   *  Constant: '<S14>/Constant1'
   *  Outport: '<Root>/HwAg'
   */
  tmpWrite = Lim_f32( (float32)rtb_Add_f, (float32)HWAGMINVAL_HWDEG_F32,
                     (float32)HWAGMAXVAL_HWDEG_F32);

  /* S-Function (Lim_f32): '<S15>/Lim_f32' incorporates:
   *  Constant: '<S15>/Constant'
   *  Constant: '<S15>/Constant1'
   *  Outport: '<Root>/RackPosn'
   */
  tmpWrite_7 = Lim_f32( (float32)rtb_FixdToFloat_f32_s16_p, (float32)
                       RACKPOSNMINVAL_MILLIMTR_F32, (float32)
                       RACKPOSNMAXVAL_MILLIMTR_F32);

  /* S-Function (Lim_f32): '<S16>/Lim_f32' incorporates:
   *  Constant: '<S16>/Constant'
   *  Constant: '<S16>/Constant1'
   *  Constant: '<S23>/Constant'
   *  Constant: '<S30>/Constant'
   *  Constant: '<S30>/Constant1'
   *  Outport: '<Root>/RoadWhlAg'
   *  S-Function (FixdToFloat_f32_s16): '<S23>/FixdToFloat_f32_s16'
   *  S-Function (LnrIntrpn_s16_s16VariXs16VariY): '<S30>/LnrIntrpn_s16_s16VariXs16VariY'
   */
  tmpWrite_9 = Lim_f32( (float32)FixdToFloat_f32_s16( (sint16)((sint16)
    LnrIntrpn_s16_s16VariXs16VariY((const sint16*)
    Rte_Prm_SysKineAndEffRackPosScaY_Ary1D(), (const sint16*)
    Rte_Prm_SysKineAndEffRoadWhlFromRackPosScaY_Ary1D(),(uint16)21U,
    rtb_LnrIntrpn_s16_s16VariXs16Va)), (float32)((float32)
    NXTRFIXDPT_P13TOFLOAT_ULS_F32)), (float32)ROADWHLAGMINVAL_RAD_F32, (float32)
                       ROADWHLAGMAXVAL_RAD_F32);

  /* S-Function (Lim_f32): '<S17>/Lim_f32' incorporates:
   *  Constant: '<S17>/Constant'
   *  Constant: '<S17>/Constant1'
   *  Outport: '<Root>/SysKineRat'
   */
  tmpWrite_c = Lim_f32( (float32)rtb_Divide, (float32)
                       SYSKINERATMINVAL_MOTDEGPERHWDEG_F32, (float32)
                       SYSKINERATMAXVAL_MOTDEGPERHWDEG_F32);

  /* S-Function (Lim_f32): '<S18>/Lim_f32' incorporates:
   *  Constant: '<S18>/Constant'
   *  Constant: '<S18>/Constant1'
   *  Outport: '<Root>/RackVel'
   */
  tmpWrite_8 = Lim_f32( (float32)rtb_Product_h, (float32)
                       RACKVELMINVAL_MILLIMTRPERSEC_F32, (float32)
                       RACKVELMAXVAL_MILLIMTRPERSEC_F32);

  /* S-Function (Lim_f32): '<S19>/Lim_f32' incorporates:
   *  Constant: '<S19>/Constant'
   *  Constant: '<S19>/Constant1'
   *  Outport: '<Root>/MotToRackInstsEff'
   */
  tmpWrite_2 = Lim_f32( (float32)rtb_FixdToFloat_f32_u16_b, (float32)
                       MOTTORACKINSTSEFFMINVAL_ULS_F32, (float32)
                       MOTTORACKINSTSEFFMAXVAL_ULS_F32);

  /* S-Function (Lim_f32): '<S20>/Lim_f32' incorporates:
   *  Constant: '<S20>/Constant'
   *  Constant: '<S20>/Constant1'
   *  Outport: '<Root>/MotToRackFInstsRat'
   */
  tmpWrite_1 = Lim_f32( (float32)rtb_Product1, (float32)
                       MOTTORACKFINSTSRATMINVAL_RACKNWTPERMOTNWTMTR_F32,
                       (float32)MOTTORACKFINSTSRATMAXVAL_RACKNWTPERMOTNWTMTR_F32);

  /* S-Function (Lim_f32): '<S21>/Lim_f32' incorporates:
   *  Constant: '<S21>/Constant'
   *  Constant: '<S21>/Constant1'
   *  Outport: '<Root>/PinionAgToRackPosnInstsRat'
   */
  tmpWrite_4 = Lim_f32( (float32)rtb_FixdToFloat_f32_u16_p, (float32)
                       PINIONAGTORACKPOSNINSTRATMINVAL_RACKMILLIMTRPERHWRAD_F32,
                       (float32)
                       PINIONAGTORACKPOSNINSTRATMAXVAL_RACKMILLIMTRPERHWRAD_F32);

  /* S-Function (Lim_f32): '<S22>/Lim_f32' incorporates:
   *  Constant: '<S22>/Constant'
   *  Constant: '<S22>/Constant1'
   *  Constant: '<S26>/Constant'
   *  Constant: '<S31>/Constant'
   *  Constant: '<S31>/Constant1'
   *  Outport: '<Root>/SteerArmLen'
   *  S-Function (FixdToFloat_f32_u16): '<S26>/FixdToFloat_f32_u16'
   *  S-Function (LnrIntrpn_u16_s16VariXu16VariY): '<S31>/LnrIntrpn_u16_s16VariXu16VariY'
   */
  tmpWrite_a = Lim_f32( (float32)FixdToFloat_f32_u16( (uint16)((uint16)
    LnrIntrpn_u16_s16VariXu16VariY((const sint16*)
    Rte_Prm_SysKineAndEffRackPosScaY_Ary1D(), (const uint16*)
    Rte_Prm_SysKineAndEffSteerArmLenFromRackPosScaY_Ary1D(),(uint16)21U,
    rtb_LnrIntrpn_s16_s16VariXs16Va)), (float32)((float32)
    NXTRFIXDPT_P15TOFLOAT_ULS_F32)), (float32)STEERARMLENMINVAL_MILLIMTR_F32,
                       (float32)STEERARMLENMAXVAL_MILLIMTR_F32);

  /* End of Outputs for RootInportFunctionCallGenerator: '<Root>/RootFcnCall_InsertedFor_call_SysKineAndEffPer1_at_outport_1' */

  /* Outport: '<Root>/HwAg' */
  (void) Rte_Write_HwAg_Val(tmpWrite);

  /* Outport: '<Root>/HwVel' */
  (void) Rte_Write_HwVel_Val(tmpWrite_0);

  /* Outport: '<Root>/MotToRackFInstsRat' */
  (void) Rte_Write_MotToRackFInstsRat_Val(tmpWrite_1);

  /* Outport: '<Root>/MotToRackInstsEff' */
  (void) Rte_Write_MotToRackInstsEff_Val(tmpWrite_2);

  /* Outport: '<Root>/PinionAgToRackInstsEff' */
  (void) Rte_Write_PinionAgToRackInstsEff_Val(tmpWrite_3);

  /* Outport: '<Root>/PinionAgToRackPosnInstsRat' */
  (void) Rte_Write_PinionAgToRackPosnInstsRat_Val(tmpWrite_4);

  /* Outport: '<Root>/PinionTqToRackFInstsRat' */
  (void) Rte_Write_PinionTqToRackFInstsRat_Val(tmpWrite_5);

  /* Outport: '<Root>/PinionVel' */
  (void) Rte_Write_PinionVel_Val(tmpWrite_6);

  /* Outport: '<Root>/RackPosn' */
  (void) Rte_Write_RackPosn_Val(tmpWrite_7);

  /* Outport: '<Root>/RackVel' */
  (void) Rte_Write_RackVel_Val(tmpWrite_8);

  /* Outport: '<Root>/RoadWhlAg' */
  (void) Rte_Write_RoadWhlAg_Val(tmpWrite_9);

  /* Outport: '<Root>/SteerArmLen' */
  (void) Rte_Write_SteerArmLen_Val(tmpWrite_a);

  /* Outport: '<Root>/SysAssiTqRat' */
  (void) Rte_Write_SysAssiTqRat_Val(tmpWrite_b);

  /* Outport: '<Root>/SysKineRat' */
  (void) Rte_Write_SysKineRat_Val(tmpWrite_c);

  /* Outport: '<Root>/SysTqRat' */
  (void) Rte_Write_SysTqRat_Val(tmpWrite_d);
}

/* Model initialize function */
FUNC(void, SysKineAndEff_CODE) SysKineAndEff_Init(void)
{
  /* (no initialization code required) */
}

#define SysKineAndEff_STOP_SEC_CODE
#include "SysKineAndEff_MemMap.h"

/*
 * File trailer for generated code.
 *
 * [EOF]
 */
