/**********************************************************************************************************************
* Copyright 2017 Nxtr 
* Nxtr Confidential
*
* Module File Name: CDD_XcpIfXcpEveCh2MilliSec.c
* Module Description: XCP Event source code that is generated by XcpIf
* Project           : BMW
* Author            : Kevin Smith
***********************************************************************************************************************
* Version Control:
* %version:          1 %
* %derived_by:       cz7lt6 %
*----------------------------------------------------------------------------------------------------------------------
* Date      Rev      Author         Change Description                                                           SCR #
* -------   -------  --------  ---------------------------------------------------------------------------     --------
* 11/01/17  1        KJS       Initial version of this generation template.                                   EA4#<TBD>
**********************************************************************************************************************/

#include "Rte_CDD_XcpIfXcpEveCh2MilliSec.h"
#include "CDD_XcpIf_Cfg_private.h"

/******************************************** File Level Rule Deviations *********************************************/

/******************************************* Module Specific Data Types **********************************************/

typedef struct {
    uint16 XcpEve_u16;
} XcpEveRec;

/******************************************** Module Specific Variables **********************************************/

/******************************************** Local Function Prototypes **********************************************/

/*********************************************** Function Definitions ************************************************/
FUNC(void, CDD_XcpIfXcpEveCh2MilliSec_CODE) CDD_XcpIfXcpEveCh2MilliSecPer1(void)
{
    VAR(XcpEveRec, AUTOMATIC) Prm_Cnt_T_str;
    if( XCPIF_XCPOSAPPL_CNT_U08 == GetApplicationID() )
    {
        Xcp_Event(XcpConf_XcpEventChannel_XcpEveCh2MilliSec);
    }
    else
    {
        Prm_Cnt_T_str.XcpEve_u16 = XcpConf_XcpEventChannel_XcpEveCh2MilliSec;
        (void)Os_CallNonTrustedFunction((Os_NonTrustedFunctionIndexType)NtWrapS_Xcp_Event, &Prm_Cnt_T_str);
    }
    
    return;
}
