/******************************************************************************
 Memory Mapping Header Darh_MemMap.h
 
 This file is generated - DO NOT EDIT MANUALLY !!!
 
 Generated by: Bergamo 2017a
 
 ******************************************************************************/
 


/*-------------------------------------------------------------------
  Darh memory sections
-------------------------------------------------------------------*/
// Darh_START_SEC_CODE
#ifdef Darh_START_SEC_CODE
#undef Darh_START_SEC_CODE
#define START_SEC_CODE
#include "MemMap.h"
#endif

#ifdef Darh_STOP_SEC_CODE
#undef Darh_STOP_SEC_CODE
#define STOP_SEC_CODE
#include "MemMap.h"
#endif
// Darh_START_SEC_CONST_SAVED_RECOVERY_ZONE
#ifdef Darh_START_SEC_CONST_SAVED_RECOVERY_ZONE
#undef Darh_START_SEC_CONST_SAVED_RECOVERY_ZONE

#endif

#ifdef Darh_STOP_SEC_CONST_SAVED_RECOVERY_ZONE
#undef Darh_STOP_SEC_CONST_SAVED_RECOVERY_ZONE

#endif
// Darh_START_SEC_CONST_UNSPECIFIED
#ifdef Darh_START_SEC_CONST_UNSPECIFIED
#undef Darh_START_SEC_CONST_UNSPECIFIED

#endif

#ifdef Darh_STOP_SEC_CONST_UNSPECIFIED
#undef Darh_STOP_SEC_CONST_UNSPECIFIED

#endif
// Darh_START_SEC_VAR_INIT_8
#ifdef Darh_START_SEC_VAR_INIT_8
#undef Darh_START_SEC_VAR_INIT_8
#define OS_START_SEC_Appl10_VAR_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef Darh_STOP_SEC_VAR_INIT_8
#undef Darh_STOP_SEC_VAR_INIT_8
#define OS_STOP_SEC_Appl10_VAR_UNSPECIFIED
#include "MemMap.h"
#endif
// Darh_START_SEC_VAR_NO_INIT_16
#ifdef Darh_START_SEC_VAR_NO_INIT_16
#undef Darh_START_SEC_VAR_NO_INIT_16
#define OS_START_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef Darh_STOP_SEC_VAR_NO_INIT_16
#undef Darh_STOP_SEC_VAR_NO_INIT_16
#define OS_STOP_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif
// Darh_START_SEC_VAR_NO_INIT_8
#ifdef Darh_START_SEC_VAR_NO_INIT_8
#undef Darh_START_SEC_VAR_NO_INIT_8
#define OS_START_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef Darh_STOP_SEC_VAR_NO_INIT_8
#undef Darh_STOP_SEC_VAR_NO_INIT_8
#define OS_STOP_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif
// Darh_START_SEC_VAR_NO_INIT_BOOLEAN
#ifdef Darh_START_SEC_VAR_NO_INIT_BOOLEAN
#undef Darh_START_SEC_VAR_NO_INIT_BOOLEAN
#define OS_START_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef Darh_START_SEC_VAR_SAVED_ZONE_BOOLEAN
#undef Darh_START_SEC_VAR_SAVED_ZONE_BOOLEAN
#define OS_START_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef Darh_STOP_SEC_VAR_SAVED_ZONE_BOOLEAN
#undef Darh_STOP_SEC_VAR_SAVED_ZONE_BOOLEAN
#define OS_STOP_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef Darh_STOP_SEC_VAR_NO_INIT_BOOLEAN
#undef Darh_STOP_SEC_VAR_NO_INIT_BOOLEAN
#define OS_STOP_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif
// Darh_START_SEC_VAR_NO_INIT_UNSPECIFIED
#ifdef Darh_START_SEC_VAR_NO_INIT_UNSPECIFIED
#undef Darh_START_SEC_VAR_NO_INIT_UNSPECIFIED
#define OS_START_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef Darh_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#undef Darh_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#define OS_STOP_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif
// Darh_START_SEC_VAR_SAVED_ZONE_16
#ifdef Darh_START_SEC_VAR_SAVED_ZONE_16
#undef Darh_START_SEC_VAR_SAVED_ZONE_16
#define OS_START_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef Darh_STOP_SEC_VAR_SAVED_ZONE_16
#undef Darh_STOP_SEC_VAR_SAVED_ZONE_16
#define OS_STOP_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif
// Darh_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
#ifdef Darh_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
#undef Darh_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
#define OS_START_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef Darh_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED
#undef Darh_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED
#define OS_STOP_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif



