/******************************************************************************
 Memory Mapping Header Omc_MemMap.h
 
 This file is generated - DO NOT EDIT MANUALLY !!!
 
 Generated by: Bergamo 2017a
 
 ******************************************************************************/
 


/*-------------------------------------------------------------------
  Omc memory sections
-------------------------------------------------------------------*/
// Omc_START_SEC_CODE
#ifdef Omc_START_SEC_CODE
#undef Omc_START_SEC_CODE
#define START_SEC_CODE
#include "MemMap.h"
#endif

#ifdef Omc_STOP_SEC_CODE
#undef Omc_STOP_SEC_CODE
#define STOP_SEC_CODE
#include "MemMap.h"
#endif
// Omc_START_SEC_CONST_SAVED_RECOVERY_ZONE
#ifdef Omc_START_SEC_CONST_SAVED_RECOVERY_ZONE
#undef Omc_START_SEC_CONST_SAVED_RECOVERY_ZONE

#endif

#ifdef Omc_STOP_SEC_CONST_SAVED_RECOVERY_ZONE
#undef Omc_STOP_SEC_CONST_SAVED_RECOVERY_ZONE

#endif
// Omc_START_SEC_CONST_UNSPECIFIED
#ifdef Omc_START_SEC_CONST_UNSPECIFIED
#undef Omc_START_SEC_CONST_UNSPECIFIED

#endif

#ifdef Omc_STOP_SEC_CONST_UNSPECIFIED
#undef Omc_STOP_SEC_CONST_UNSPECIFIED

#endif
// Omc_START_SEC_VAR_NO_INIT_BOOLEAN
#ifdef Omc_START_SEC_VAR_NO_INIT_BOOLEAN
#undef Omc_START_SEC_VAR_NO_INIT_BOOLEAN
#define OS_START_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef Omc_STOP_SEC_VAR_NO_INIT_BOOLEAN
#undef Omc_STOP_SEC_VAR_NO_INIT_BOOLEAN
#define OS_STOP_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif
// Omc_START_SEC_VAR_NO_INIT_UNSPECIFIED
#ifdef Omc_START_SEC_VAR_NO_INIT_UNSPECIFIED
#undef Omc_START_SEC_VAR_NO_INIT_UNSPECIFIED
#define OS_START_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef Omc_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#undef Omc_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#define OS_STOP_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif
// Omc_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
#ifdef Omc_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
#undef Omc_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
#define OS_START_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef Omc_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED
#undef Omc_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED
#define OS_STOP_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef Omc_START_SEC_VAR_INIT_UNSPECIFIED
#undef Omc_START_SEC_VAR_INIT_UNSPECIFIED
#define OS_START_SEC_Appl10_VAR_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef Omc_STOP_SEC_VAR_INIT_UNSPECIFIED
#undef Omc_STOP_SEC_VAR_INIT_UNSPECIFIED
#define OS_STOP_SEC_Appl10_VAR_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef Omc_START_SEC_VAR_INIT_BOOLEAN
#undef Omc_START_SEC_VAR_INIT_BOOLEAN
#define OS_START_SEC_Appl10_VAR_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef Omc_STOP_SEC_VAR_INIT_BOOLEAN
#undef Omc_STOP_SEC_VAR_INIT_BOOLEAN
#define OS_STOP_SEC_Appl10_VAR_UNSPECIFIED
#include "MemMap.h"
#endif

