/******************************************************************************
 Memory Mapping Header Srv_MemMap.h
 
 This file is generated - DO NOT EDIT MANUALLY !!!
 
 Generated by: Bergamo 2017a
 
 ******************************************************************************/
 


/*-------------------------------------------------------------------
  Srv memory sections
-------------------------------------------------------------------*/
// Srv_START_SEC_CODE
#ifdef Srv_START_SEC_CODE
#undef Srv_START_SEC_CODE
#define START_SEC_CODE
#include "MemMap.h"
#endif

#ifdef Srv_STOP_SEC_CODE
#undef Srv_STOP_SEC_CODE
#define STOP_SEC_CODE
#include "MemMap.h"
#endif
// Srv_START_SEC_CONST_SHARED_BM_DATA
#ifdef Srv_START_SEC_CONST_SHARED_BM_DATA
#undef Srv_START_SEC_CONST_SHARED_BM_DATA

#endif

#ifdef Srv_STOP_SEC_CONST_SHARED_BM_DATA
#undef Srv_STOP_SEC_CONST_SHARED_BM_DATA

#endif
// Srv_START_SEC_VAR_NOINIT_BOOT_STATUS
#ifdef Srv_START_SEC_VAR_NOINIT_BOOT_STATUS
#undef Srv_START_SEC_VAR_NOINIT_BOOT_STATUS
#define OS_START_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef Srv_STOP_SEC_VAR_NOINIT_BOOT_STATUS
#undef Srv_STOP_SEC_VAR_NOINIT_BOOT_STATUS
#define OS_STOP_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif



