/******************************************************************************
 Memory Mapping Header StdDiag_MemMap.h
 
 This file is generated - DO NOT EDIT MANUALLY !!!
 
 Generated by: Bergamo 2017a
 
 ******************************************************************************/
 


/*-------------------------------------------------------------------
  StdDiag memory sections
-------------------------------------------------------------------*/
// StdDiag_START_SEC_CODE
#ifdef StdDiag_START_SEC_CODE
#undef StdDiag_START_SEC_CODE
#define START_SEC_CODE
#include "MemMap.h"
#endif

#ifdef StdDiag_STOP_SEC_CODE
#undef StdDiag_STOP_SEC_CODE
#define STOP_SEC_CODE
#include "MemMap.h"
#endif
// StdDiag_START_SEC_CONST_UNSPECIFIED
#ifdef StdDiag_START_SEC_CONST_UNSPECIFIED
#undef StdDiag_START_SEC_CONST_UNSPECIFIED

#endif

#ifdef StdDiag_STOP_SEC_CONST_UNSPECIFIED
#undef StdDiag_STOP_SEC_CONST_UNSPECIFIED

#endif
// StdDiag_START_SEC_VAR_INIT_BOOLEAN
#ifdef StdDiag_START_SEC_VAR_INIT_BOOLEAN
#undef StdDiag_START_SEC_VAR_INIT_BOOLEAN
#define OS_START_SEC_Appl10_VAR_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef StdDiag_STOP_SEC_VAR_INIT_BOOLEAN
#undef StdDiag_STOP_SEC_VAR_INIT_BOOLEAN
#define OS_STOP_SEC_Appl10_VAR_UNSPECIFIED
#include "MemMap.h"
#endif
// StdDiag_START_SEC_VAR_INIT_UNSPECIFIED
#ifdef StdDiag_START_SEC_VAR_INIT_UNSPECIFIED
#undef StdDiag_START_SEC_VAR_INIT_UNSPECIFIED
#define OS_START_SEC_Appl10_VAR_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef StdDiag_STOP_SEC_VAR_INIT_UNSPECIFIED
#undef StdDiag_STOP_SEC_VAR_INIT_UNSPECIFIED
#define OS_STOP_SEC_Appl10_VAR_UNSPECIFIED
#include "MemMap.h"
#endif
// StdDiag_START_SEC_VAR_NO_INIT_16
#ifdef StdDiag_START_SEC_VAR_NO_INIT_16
#undef StdDiag_START_SEC_VAR_NO_INIT_16
#define OS_START_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef StdDiag_STOP_SEC_VAR_NO_INIT_16
#undef StdDiag_STOP_SEC_VAR_NO_INIT_16
#define OS_STOP_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif
// StdDiag_START_SEC_VAR_NO_INIT_8
#ifdef StdDiag_START_SEC_VAR_NO_INIT_8
#undef StdDiag_START_SEC_VAR_NO_INIT_8
#define OS_START_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef StdDiag_STOP_SEC_VAR_NO_INIT_8
#undef StdDiag_STOP_SEC_VAR_NO_INIT_8
#define OS_STOP_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif
// StdDiag_START_SEC_VAR_NO_INIT_BOOLEAN
#ifdef StdDiag_START_SEC_VAR_NO_INIT_BOOLEAN
#undef StdDiag_START_SEC_VAR_NO_INIT_BOOLEAN
#define OS_START_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef StdDiag_STOP_SEC_VAR_NO_INIT_BOOLEAN
#undef StdDiag_STOP_SEC_VAR_NO_INIT_BOOLEAN
#define OS_STOP_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif
// StdDiag_START_SEC_VAR_NO_INIT_UNSPECIFIED
#ifdef StdDiag_START_SEC_VAR_NO_INIT_UNSPECIFIED
#undef StdDiag_START_SEC_VAR_NO_INIT_UNSPECIFIED
#define OS_START_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef StdDiag_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#undef StdDiag_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#define OS_STOP_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif



