/******************************************************************************
 Memory Mapping Header Stm_MemMap.h
 
 This file is generated - DO NOT EDIT MANUALLY !!!
 
 Generated by: Bergamo 2017a
 
 ******************************************************************************/
 


/*-------------------------------------------------------------------
  Stm memory sections
-------------------------------------------------------------------*/
// Stm_START_SEC_CODE
#ifdef Stm_START_SEC_CODE
#undef Stm_START_SEC_CODE
#define START_SEC_CODE
#include "MemMap.h"
#endif

#ifdef Stm_STOP_SEC_CODE
#undef Stm_STOP_SEC_CODE
#define STOP_SEC_CODE
#include "MemMap.h"
#endif
// Stm_START_SEC_CONST_UNSPECIFIED
#ifdef Stm_START_SEC_CONST_UNSPECIFIED
#undef Stm_START_SEC_CONST_UNSPECIFIED

#endif

#ifdef Stm_STOP_SEC_CONST_UNSPECIFIED
#undef Stm_STOP_SEC_CONST_UNSPECIFIED

#endif
// Stm_START_SEC_VAR_CLEARED_16
#ifdef Stm_START_SEC_VAR_CLEARED_16
#undef Stm_START_SEC_VAR_CLEARED_16
#define OS_START_SEC_Appl10_VAR_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef Stm_STOP_SEC_VAR_CLEARED_16
#undef Stm_STOP_SEC_VAR_CLEARED_16
#define OS_STOP_SEC_Appl10_VAR_UNSPECIFIED
#include "MemMap.h"
#endif
// Stm_START_SEC_VAR_CLEARED_BOOLEAN
#ifdef Stm_START_SEC_VAR_CLEARED_BOOLEAN
#undef Stm_START_SEC_VAR_CLEARED_BOOLEAN
#define OS_START_SEC_Appl10_VAR_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef Stm_STOP_SEC_VAR_CLEARED_BOOLEAN
#undef Stm_STOP_SEC_VAR_CLEARED_BOOLEAN
#define OS_STOP_SEC_Appl10_VAR_UNSPECIFIED
#include "MemMap.h"
#endif
// Stm_START_SEC_VAR_INIT_UNSPECIFIED
#ifdef Stm_START_SEC_VAR_INIT_UNSPECIFIED
#undef Stm_START_SEC_VAR_INIT_UNSPECIFIED
#define OS_START_SEC_Appl10_VAR_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef Stm_STOP_SEC_VAR_INIT_UNSPECIFIED
#undef Stm_STOP_SEC_VAR_INIT_UNSPECIFIED
#define OS_STOP_SEC_Appl10_VAR_UNSPECIFIED
#include "MemMap.h"
#endif



