/******************************************************************************
 Memory Mapping Header Vin_MemMap.h
 
 This file is generated - DO NOT EDIT MANUALLY !!!
 
 Generated by: Bergamo 2017a
 
 ******************************************************************************/
 


/*-------------------------------------------------------------------
  Vin memory sections
-------------------------------------------------------------------*/
// Vin_START_SEC_CODE
#ifdef Vin_START_SEC_CODE
#undef Vin_START_SEC_CODE
#define START_SEC_CODE
#include "MemMap.h"
#endif

#ifdef Vin_STOP_SEC_CODE
#undef Vin_STOP_SEC_CODE
#define STOP_SEC_CODE
#include "MemMap.h"
#endif
// Vin_START_SEC_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED
#ifdef Vin_START_SEC_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED
#undef Vin_START_SEC_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED

#endif

#ifdef Vin_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED
#undef Vin_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED

#endif
// Vin_START_SEC_VAR_NO_INIT_32
#ifdef Vin_START_SEC_VAR_NO_INIT_32
#undef Vin_START_SEC_VAR_NO_INIT_32
#define OS_START_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef Vin_STOP_SEC_VAR_NO_INIT_32
#undef Vin_STOP_SEC_VAR_NO_INIT_32
#define OS_STOP_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif
// Vin_START_SEC_VAR_NO_INIT_8
#ifdef Vin_START_SEC_VAR_NO_INIT_8
#undef Vin_START_SEC_VAR_NO_INIT_8
#define OS_START_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef Vin_STOP_SEC_VAR_NO_INIT_8
#undef Vin_STOP_SEC_VAR_NO_INIT_8
#define OS_STOP_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif
// Vin_START_SEC_VAR_NO_INIT_UNSPECIFIED
#ifdef Vin_START_SEC_VAR_NO_INIT_UNSPECIFIED
#undef Vin_START_SEC_VAR_NO_INIT_UNSPECIFIED
#define OS_START_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef Vin_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#undef Vin_STOP_SEC_VAR_NO_INIT_UNSPECIFIED
#define OS_STOP_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif
// Vin_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
#ifdef Vin_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
#undef Vin_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
#define OS_START_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif

#ifdef Vin_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED
#undef Vin_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED
#define OS_STOP_SEC_Appl10_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h"
#endif



