#include "rsent_regs.h"

#define RSENT2MDCOMC RSENT2OMC
#define RSENT2CSCNRC RSENT2NRC
#define RSENT2CSFRS RSENT2FRS
#define RSENT2CSNRS RSENT2NRS
#define RSENT2FRXDFND RSENT2FND
#define RSENT2MSTOMS RSENT2OMS