#include "rsent_regs.h"

#define RSENT4MDCOMC RSENT4OMC
#define RSENT4CSCNRC RSENT4NRC
#define RSENT4CSFRS RSENT4FRS
#define RSENT4CSNRS RSENT4NRS
#define RSENT4FRXDFND RSENT4FND
#define RSENT4MSTOMS RSENT4OMS