/**********************************************************************************************************************
 *  FILE DESCRIPTION
 *  -------------------------------------------------------------------------------------------------------------------
 *  File: HwRefTqSum.c
 *  SW-C Type:HwRefTqSum
 *  C/C++ source code generated on : Wed Mar  7 17:59:46 2018
   Code generated for Simulink model 'HwRefTqSum'.
 ***********************************************************************************************************************
   Tool Information
 *-----------------------------------------------------------------------------------------------------------------------
 * Simulink Coder version         : 8.13 (R2017b) 24-Jul-2017
 **********************************************************************************************************************
 * Copyright '2018' Nxtr
 * Nxtr Confidential
 *
 * Module File Name  : HwRefTqSum.c
 * Module Description: Handwheel Reference Torque Summation is used to do the sum of reference
   torque generated through effort, return, damping and command overlay.
 * Project           : CBD
 * Author            : Nimmy Mathews
 ***********************************************************************************************************************
 * Version Control:
 * %version:  		2 %
 * %derived_by:     dzvc93 %
 **********************************************************************************************************************
 * CHANGE LOG COPIED FROM SIMULINK MODEL
 *---------------------------------------
 * Change Log

   Ver 1.0.1
   Author :Nimmy Mathews
   Date : 21Feb2018
   CR : EA4#20879
   Description : Updated model for Autocoding without any functionality change.

   Ver 1.0.0
   Author :Avani Shah (KPIT)
   Date : 8Dec2017
   CR : EA4#17860
   Description : Initial version from Requirment baseline 1.0
 **********************************************************************************************************************/
/*********************File Level Rule Deviations*******************************/

/* MISRA-AGC Rule 16.10 [NXTRDEV 16.10.1]: There is no appropriate action to take on the return value for Rte_Read, Rte_Write */
/* MISRA-AGC Rule 19.1  [NXTRDEV 19.1.1]:  AUTOSAR requires deviation from this rule for Memory Mapping include statements */

/* MISRA-AGC Rule 8.1   [NXTRDEV 8.1.1] :  Deviation for autocode only, due to tools limitation.
   ‘_Init’ function does not have a declaration/prototype in autocode. This init function is generated by embedded coder and is not present in the Simulink model.
   This function is always empty and is not called */

/* MISRA-AGC Rule 8.10  [NXTRDEV 8.10.2]:  Deviation for autocode only, due to tools limitation.
   ‘_Init’ function is not defined as “static” even though no external linkage is required. This init function is generated by embedded coder and is not present in the Simulink model.
   This function is always empty and is not called */
#include "HwRefTqSum.h"
#define HwRefTqSum_START_SEC_CODE
#include "HwRefTqSum_MemMap.h"

/* Exported data define */

/* Definition for custom storage class: Const_Local */
#define HWTQCMDSUMHILIM_HWNWTMTR_F32   ((float32)(10.0F))
#define HWTQCMDSUMLOLIM_HWNWTMTR_F32   ((float32)(-10.0F))

/* Model step function for TID1 */
FUNC(void, HwRefTqSum_CODE) HwRefTqSumInit1(void) /* Sample time: [0.002s, 0.0s] */
{
  /* (no output/update code required) */
}

/* Model step function for TID2 */
FUNC(void, HwRefTqSum_CODE) HwRefTqSumPer1(void) /* Sample time: [0.002s, 0.0s] */
{
  /* local block i/o variables */
  float32 rtb_Add;
  float32 tmpRead;
  float32 tmpRead_0;
  float32 tmpRead_1;
  float32 tmpRead_2;
  float32 tmpRead_3;
  float32 tmpWrite;

  /* Inport: '<Root>/HwTqCmdOvrl' */
  Rte_Read_HwTqCmdOvrl_Val(&tmpRead_3);

  /* Inport: '<Root>/RtnCmd' */
  Rte_Read_RtnCmd_Val(&tmpRead_2);

  /* Inport: '<Root>/HwTqCmdHys' */
  Rte_Read_HwTqCmdHys_Val(&tmpRead_1);

  /* Inport: '<Root>/HwTqCmdDampg' */
  Rte_Read_HwTqCmdDampg_Val(&tmpRead_0);

  /* Inport: '<Root>/HwTqCmdEffort' */
  Rte_Read_HwTqCmdEffort_Val(&tmpRead);

  /* RootInportFunctionCallGenerator: '<Root>/RootFcnCall_InsertedFor_HwRefTqSumPer1_at_outport_1' incorporates:
   *  SubSystem: '<S1>/HwRefTqSumPer1'
   */
  /* Sum: '<S4>/Add' incorporates:
   *  Constant: '<S4>/Constant'
   *  Product: '<S4>/Product'
   */
  rtb_Add = (((tmpRead + tmpRead_0) + tmpRead_1) + tmpRead_3) + (tmpRead_2 *
    Rte_Prm_SysGlbPrmSysTqRat_Val());

  /* S-Function (Lim_f32): '<S5>/Lim_f32' incorporates:
   *  Constant: '<S5>/Constant'
   *  Constant: '<S5>/Constant1'
   *  Outport: '<Root>/HwTqCmdSum'
   */
  tmpWrite = Lim_f32( (float32)rtb_Add, (float32)HWTQCMDSUMLOLIM_HWNWTMTR_F32,
                     (float32)HWTQCMDSUMHILIM_HWNWTMTR_F32);

  /* End of Outputs for RootInportFunctionCallGenerator: '<Root>/RootFcnCall_InsertedFor_HwRefTqSumPer1_at_outport_1' */

  /* Outport: '<Root>/HwTqCmdSum' */
  (void) Rte_Write_HwTqCmdSum_Val(tmpWrite);
}

/* Model initialize function */
FUNC(void, HwRefTqSum_CODE) HwRefTqSum_Init(void)
{
  /* (no initialization code required) */
}

#define HwRefTqSum_STOP_SEC_CODE
#include "HwRefTqSum_MemMap.h"

/*
 * File trailer for generated code.
 *
 * [EOF]
 */
